In [1]:
import requests
import pandas as pd
import time
import random

header = {"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}

pages = 7932
page_ids = []
for page in range(pages // 200 + 1) :
    base = f"https://ohou.se/projects.json?writer=self&page={page+1}&per=200&v=3"
    request = requests.get(base, headers=header, timeout=5)
    request_json = request.json()
    for item in request_json["projects"] :
        page_ids.append(item['id'])

len(page_ids)

7932

In [8]:
pages = pd.DataFrame(page_ids, columns=['page_id'])
pages.to_csv('page_ids.csv', index=False)

In [9]:
page_category = []
product_ids = []

count = 0

for id in page_ids :
    page = f"https://ohou.se/projects/{id}/detail.json?v=4&"
    request = requests.get(page, headers=header, timeout=5)
    request_json = request.json()['project']
    page_category.append([id, request_json['title'], request_json['created_at'], request_json['residence'], request_json['area'], 
    request_json['agent'], request_json['expertise'], request_json['family_list'], request_json['style_list'], request_json['budget']])
    for product in request_json['bucketplace_document_supplements']['products'] :
        product_ids.append([id, product['id']])

    count += 1
    if count % 100 == 0 :
        time.sleep(random.randint(10, 20))

len(page_category), len(product_ids)

(7932, 345271)

In [10]:
page_category = pd.DataFrame(page_category, columns=['page_id', 'title', 'timestamp', 'residence', 'area', 'agent', 'expertise', 'family_list', 'style_list', 'budget'])
page_category.to_csv('pages.csv', index=False)
page_category

,page_id,title,timestamp,residence,area,agent,expertise,family_list,style_list,budget
0,133556,패션 마케터의 감각으로 탈바꿈한 50살 아파트 리모델링,2023-01-03T09:36:42.000+09:00,아파트,41평,전문가,리모델링,[신혼부부],[모던],0
1,133209,같은 집 다른 느낌! 8평 오피스텔의 스타일 변천사,2023-01-03T09:36:18.000+09:00,원룸&오피스텔,8평,셀프•DIY,홈스타일링,[싱글라이프],[내추럴],0
2,134133,포근한 일상을 고스란히🕊️ 내추럴 무드 신혼집 기록,2023-01-03T08:05:46.000+09:00,단독주택,50평,셀프•DIY,홈스타일링,[신혼부부],[내추럴],0
3,133792,유럽의 미드센추리 감성 가득! 영국의 모던 하우스,2023-01-03T08:05:39.000+09:00,단독주택,43평,셀프•DIY,홈스타일링,[취학 자녀가 있는 집],[모던],0
4,133766,"30평대 신혼집, 알록달록한 패브릭으로 포인트 주기!",2023-01-03T08:05:35.000+09:00,아파트,33평,셀프•DIY,홈스타일링,[신혼부부],[유니크&믹스매치],0
...,...,...,...,...,...,...,...,...,...,...
7927,442,성마마의 신혼집~,2014-11-23T19:31:08.000+09:00,아파트,20평대,셀프•DIY,홈스타일링,[신혼부부],[내추럴],700
7928,439,최쯔비의 러브하우스♡,2014-11-22T01:02:27.000+09:00,아파트,20평대,반셀프,리모델링,[신혼부부],[내추럴],745
7929,434,여름의 기록,2014-11-20T14:08:31.000+09:00,아파트,24평,셀프•DIY,홈스타일링,[아기가 있는 집],[내추럴],0
7930,432,조금씩 더하기+,2014-11-19T18:05:29.000+09:00,아파트,20평대,반셀프,홈스타일링,[신혼부부],[내추럴],0
7931,318,감성 터지는 작은방 셀프 인테리어,2014-10-21T14:30:52.000+09:00,원룸&오피스텔,10평,셀프•DIY,홈스타일링,[싱글라이프],[유니크&믹스매치],0

In [11]:
product_ids = pd.DataFrame(product_ids, columns=['page_id', 'product_id'])
product_ids.to_csv('page_products.csv', index=False)
product_ids

        page_id  product_id
0        133556       32125
1        133556       33050
2        133556       75758
3        133556      101921
4        133556      110328
...         ...         ...
345266      318        2258
345267      318        2259
345268      318        2261
345269      318        2262
345270      318        2263

[345271 rows x 2 columns]

In [12]:
product_ids.nunique()

page_id         7861
product_id    131408
dtype: int64